// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnWwhf14pYqraaL4BLLyc59P2KYqKtces',
    appId: '1:284683349308:android:67df0f7b836af90cdb4239',
    messagingSenderId: '284683349308',
    projectId: 'emospeak-cc471',
    storageBucket: 'emospeak-cc471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm9HaiA3PeuUqdht1GEx-hyYsnWBH6-sw',
    appId: '1:284683349308:ios:4316f480c4e6ccf7db4239',
    messagingSenderId: '284683349308',
    projectId: 'emospeak-cc471',
    storageBucket: 'emospeak-cc471.appspot.com',
    androidClientId: '284683349308-io3a1bctq9gvdormd5iouk9ogcl3g39n.apps.googleusercontent.com',
    iosClientId: '284683349308-8bkp47c99b6roiub4d26bm5gfes3h82b.apps.googleusercontent.com',
    iosBundleId: 'com.example.welcomeApp',
  );
}
